[project]
name = 'amm'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 3
epoch = '3.2'

[contracts.amm]
path = 'contracts/amm.clar'
clarity_version = 3
epoch = '3.2'

[contracts.mock-token]
path = 'contracts/mock-token.clar'
clarity_version = 3
epoch = '3.2'

[contracts.mock-token-2]
path = 'contracts/mock-token.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
api_url = 'https://api.hiro.so'
